name: "mi accion"
description: "Test my action"

runs:
  using: "composite"   #para poder reutilizar

  steps: 
    - name: hola mundo
      uses: actions/checkout@v3

    - name: Checkout
      uses: actions/checkout@v4.1.7 

    

