name: Ejemplo de composite Action

on: [push]

jobs:
  say-hello2:
    runs-on: ubuntu-latest

    env:
      MY_VAR: mi variable de entorno #podemos crear variables en env y usarlas a nivel steps

    steps:
      - name: Test
        env:
          STEP_MY_VAR: Nivel step
        run: echo "Valor ${{vars.MI_VARIABLE_2}}"

      - name: Secret
        run: echo "Secret ${{secrets.MI_SECRET}}"
      
      - name: Secret ssh key
        run: |
          mdkir ~/.ssh
          echo "Secret ${{secrets.SSH_KEY}}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 127.0.1.1 >> ~/-ssh/known_hosts

          cat ~/-ssh/known_hosts