name: Ejemplo de composite Action

on: [push]

jobs:
  say-hello2:
    runs-on: ubuntu-latest

    env:
      MY_VAR: mi variable de entorno #podemos crear variables en env y usarlas a nivel steps

    steps:
      - name: Test
        env:
          STEP_MY_VAR: Nivel step
        run: echo "Valor ${{vars.MI_VARIABLE_2}}"

      - name: Secret
        run: echo "Secret ${{secrets.MI_SECRET}}"
        